### ISSUE TITLE
Support left anchored browsing

### ISSUE THREAD

**Issue by kirkhess** [LD4P/qa_server#190]
ID supports a suggest service, which returns results in alphabetical order and allows a typeahead so if you type "Animation" it will return all the labels which start with Animation not the labels which contain Animation.

There's already a request here (https://github.com/LD4P/sinopia_editor/issues/1251) which is asking for the results to be in alpha order.

Suggest example:
https://id.loc.gov/authorities/subjects/suggest/?count=100&q=Library%20Buildings

BFE display example:
![image](https://user-images.githubusercontent.com/1419922/64859405-22905200-d5f8-11e9-8243-3ce851e2e497.png)

**Comment by michelleif** [comment]
more feedback from Stanford cataloging team requesting left-anchored search:

**Comment by michelleif** [comment]
in #238 we say that left-anchored search would require UI change in Sinopia, but is there a way to do it without UI changes? by allowing the user to use special characters to indicate what they want, like `!abc` means left-anchored but `abc` means find anywhere?

**Comment by elrayle** [comment]
I marked this low priority.  Indexing changes are underway to support parentheses, hyphens, diacritics, etc.  This type of indexing change is more complex and is lower in priority than the changes currently being worked on.

If the left-anchor can be encoded in the search string, it would mean that the only change would happen at the cache level.  Otherwise, all levels of the app (i.e., cache, qa, sinopia) would have to be updated.

@sfolsom What is the priority of this in the community?

**Comment by elrayle** [comment]
This and several other similar issues related to ordering of results or the approach to performing the search are marked as low priority.  This issue is being closed as `wontfix`, but can be reopened if it becomes a priority.

See also: 
* Issue #203
* Issue #134
