### ISSUE TITLE
Improve behavior of Description authentication and Description conventions in sinopia:resourceTemplate:bf2:Agents:AdminMetadata

### ISSUE THREAD

**Issue by dezel002** [LD4P/qa_server#231]
In the base Admin Metadata RT, there are a couple of things that would make it more usable.

1. Description authentication: in the dropdown list, add acronyms in parentheses for all sources following the spelled out name. Both here and in Description conventions, it's very inconsistent. Both the spelled out form and the acronym should appear in all cases. Catalogers typically think of them by their abbreviations, so that's the first instinct in entering as a search. Example Program for Cooperative Cataloging (PCC)

2. Description authentication
a) Same issue as above regarding abbreviations and spelled out names
b) Allow for entering more than one. It is common in Rare Materials cataloging to use both RDA and one of the DCRM modules. I can't see a way to enter both here
c) There is an outdated reference to the rare books cataloging manual. The current standard is Descriptive Cataloging of Rare Materials (Books) (DCRM(B)), not Descriptive Cataloging of Rare Books

**Comment by sfolsom** [comment]
1.) I'm not sure what is meant by Description Authentication; I don't see it in the RT. It seems to either be an issue the LC list lookup ("http://id.loc.gov/vocabulary/descriptionConventions", it's not using QA) in the resource template, or... something with Sinopia accounts attributed to descriptions. [Sorry I can get sinopia:resourceTemplate:bf2:Agents:AdminMetadata to open on stage, so I'm just reading the json template.]

Where is the current version of sinopia:resourceTemplate:bf2:Agents:AdminMetadata?

**Comment by michelleif** [comment]
hi @dezel002 my bad on the above, these 2 vocabularies are not served through QA, Sinopia gets the values directly from id.loc.gov, so you will need to ask LC if they could add the acronyms to the label, and give them the feedback about the outdated value. So I'm going to close this since no Sinopia or QA development is required. (We are working on getting those LC vocabularies into QA which would allow more control, like showing a label with the acronym, but we don't have a timeframe on that.)
