### ISSUE TITLE
Refactor QA term request to return json-ld

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#29]
### QA refactor
In support of terms that will have their details copied into a Sinopia entity, QA should have the ability to return a term as json-ld serialization instead of normalized json.  The full details of how Sinopia will import an external term is TBA (see proposed process below).  It is anticipated that the ontology for the json-ld will need to match the ontology of the Profile selected for Sinopia entity being created.

### Basic Process for importing QA term into Sinopia 
(discussed at the LD4P meetings)

* in Sinopia, select a Profile for creating an entity
* in Sinopia, search a QA authority (e.g. ShareVDE, LC, Discogs, etc.)
* in Sinopia, select the QA term to import
* in Sinopia, request the term from QA with format=jsonld
* QA returns jsonld for the term
* in Sinopia, fill the fields based on the mapping of the Profile to the jsonld returned by QA
* data that is unable to be mapped to a Profile field will be displayed in the Sinopia form in a readonly textarea
* in Sinopia, edits are made and the entity is saved (note that readonly data is not saved)

**Comment by elrayle** [comment]
@jermnelson @jgreben Can you review the Basic Process for importing QA term into Sinopia and see if this is your understanding as well?  The list of steps is based on our conversation at the LD4P meetings earlier this week.

**Comment by jgreben** [comment]
@elrayle 

In consultation with @jermnelson:

`QA should have the ability to return a term as json-ld serialization instead of normalized json.` 
- Yes, we think this is true

`It is anticipated that the ontology for the json-ld will need to match the ontology of the Profile selected for Sinopia entity being created.`
- We are not sure about this. Instead of "will need to match" we think it should "MAY need to match." If the imported data uses an ontology that does not match the chosen profile, we will display the un-matched triples as described in bullet points 7 and 8 with the possibility of allowing the triples to be preserved as an option. This is still work in Sinopia that needs to be discussed and worked out.
