### ISSUE TITLE
New Indexing: GEONAMES - changes in accuracy tests

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#394]
The new indexing scheme has the following impact on GEONAMES accuracy tests:

![image](https://user-images.githubusercontent.com/6855473/101539282-4c0b6b00-396c-11eb-8f25-efeec4371b25.png)

**Comment by sfolsom** [comment]
@elrayle Do blanks mean they aren't showing up at all? Because I see https://sws.geonames.org/3017382/ as the 4th result here: https://lookup.ld4l.org/authorities/search/linked_data/geonames_direct?q=France&maxRecords=15. And https://sws.geonames.org/5128581/ is in the top 15 for (though not the 3rd position). @eichmann, it looks like we might want to weigh the value in gn:name higher. The gn:alternateName is jumping ahead in the results when it shouldn't.

**Comment by elrayle** [comment]
Action: @sfolsom will change 'New York' search to 'New York City'

Action: @elrayle will explore why 'France' does not pass while the expected URI returns as the second result.

**Comment by sfolsom** [comment]
Test for New York City has been made: https://github.com/LD4P/qa_server/pull/409

**Comment by elrayle** [comment]
ACTION: @elrayle will push New York change to lookup-int.

**Comment by elrayle** [comment]
@eichmann The following `curl` requests 8 records, but gets back 1000.

```
curl -L -D - -H 'Accept: application/n-triples' 'http://wintermute.slis.uiowa.edu:8081/ld4l_services/geonames_batch.jsp?query=New%20York%20City&entity=all&maxRecords=8&startRecord=1&lang=en'
```

**Comment by elrayle** [comment]
Closing this as the tests now all pass.  Opened Issue #413 to address the number of returned results.
