### ISSUE TITLE
query results should allow for matches using stemming

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#99]
The index can support stemming (e.g. exit matches exit, exits, exiting, exited).

Reported by @michelleif in slack 05-30-2019
>related question re lookup to LOC Demographics, “worker” gives 0 results even though there are results with “workers”, same with search for “librarian” and you get 0 but “librarians”. is this expected behavior?

With and without an 's' is a clear stemming example that should be straightforward to resolve.

Reported by @michelleif in slack 05-30-2019
>if you type `coffe` in a lookup to LOC subjects you don’t get any `coffee` matches, you have to type the whole word `coffee`

This one is less clear and may require discussion to determine the appropriate way to move forward.

**Comment by sfolsom** [comment]
Would this issue cover support for type ahead with incomplete words, e.g. "vonnegu" bringing back "Vonnegut"?

**Comment by elrayle** [comment]
Partial matches are described in issue #134

**Comment by sfolsom** [comment]
Tests for stemming for demographics: https://github.com/LD4P/qa_server/pull/370.

**Comment by eichmann** [comment]
@sfolsom which authorities should I stem?  By default under the new scheme I'm not stemming.

**Comment by sfolsom** [comment]
- [ ] SVDE Institutional Data (because there are no subauthorities for Persons, places, etc.), only titles on Works, Instances, Hubs


- [ ] LCSH


- [ ] LCGFT


- [ ] Getty AAT 


- [ ] Ligatus


- [ ] FAST Schema:Intangibles (if we can stem on only a subauthority, if it's a lot of work, I wouldn't worry too much about this)


- [ ] LCDGT


- [ ] LOC small vocabularies (the ones at http://id.loc.gov/download/ that are billed as Cataloging vocabularies)


- [ ] OLAC 


- [ ] RBMS Vocabs


There may be more vocabs that will perform better with stemming, and some of these listed above may need to revert back to non-stemming if searches become difficult, but this is a start.

**Comment by elrayle** [comment]
I believe that stemming is in place.  The following queries return the same results.

https://lookup.ld4l.org/authorities/search/linked_data/locdemographics_ld4l_cache?q=dancer&maxRecords=5
https://lookup.ld4l.org/authorities/search/linked_data/locdemographics_ld4l_cache?q=dancers&maxRecords=5
https://lookup.ld4l.org/authorities/search/linked_data/locdemographics_ld4l_cache?q=dancered&maxRecords=5
https://lookup.ld4l.org/authorities/search/linked_data/locdemographics_ld4l_cache?q=dancering&maxRecords=5

@dave Is the same searching used across authorities?  
@sfolsom Are there other tests you want to run before we close this?

**Comment by eichmann** [comment]
Yes, all authorities use a common indexing stack and a common retrieval stack.
